stop tagging when finishing hotfix

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -283,21 +283,21 @@ cmd_finish() {
 		  # TODO: What do we do now?
 	fi
 
-	if noflag notag; then
-		# try to tag the release
-		# in case a previous attempt to finish this release branch has failed,
-		# but the tag was set successful, we skip it now
-		local tagname=$VERSION_PREFIX$VERSION
-		if ! git_tag_exists "$tagname"; then
-			local opts="-a"
-			flag sign && opts="$opts -s"
-			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
-			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
-			[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
-			eval git_do tag $opts "$VERSION_PREFIX$VERSION" "$BRANCH" || \
-			die "Tagging failed. Please run finish again to retry."
-		fi
-	fi
+	# if noflag notag; then
+	# 	# try to tag the release
+	# 	# in case a previous attempt to finish this release branch has failed,
+	# 	# but the tag was set successful, we skip it now
+	# 	local tagname=$VERSION_PREFIX$VERSION
+	# 	if ! git_tag_exists "$tagname"; then
+	# 		local opts="-a"
+	# 		flag sign && opts="$opts -s"
+	# 		[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
+	# 		[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
+	# 		[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
+	# 		eval git_do tag $opts "$VERSION_PREFIX$VERSION" "$BRANCH" || \
+	# 		die "Tagging failed. Please run finish again to retry."
+	# 	fi
+	# fi
 
 	# try to merge into develop
 	# in case a previous attempt to finish this release branch has failed,
