new command `hotfix lc`, which merges hotfix branch into `lcheck` branch.

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -348,7 +348,7 @@ cmd_finish() {
 	echo
 }
 
-# cmd_finish - `merge into master` - tagging - delete branch
+# cmd_examine - `merge into develop`
 cmd_examine() {
 	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
 	DEFINE_boolean sign false "sign the release tag cryptographically" s
@@ -422,6 +422,84 @@ cmd_examine() {
 	# fi
 	if flag push; then
 		echo "- '$DEVELOP_BRANCH' have been pushed to '$ORIGIN'"
+	fi
+	echo
+}
+
+# cmd_lc - `merge into lcheck`
+cmd_lc() {
+	DEFINE_boolean fetch false "fetch from $ORIGIN before performing lcheck" F
+	DEFINE_boolean sign false "sign the release tag cryptographically" s
+	DEFINE_string signingkey "" "use the given GPG-key for the digital signature (implies -s)" u
+	# DEFINE_string message "" "use the given tag message" m
+	# DEFINE_string messagefile "" "use the contents of the given file as tag message" f
+	DEFINE_boolean push false "push to $ORIGIN after performing finish" p
+	# DEFINE_boolean keep false "keep branch after performing finish" k
+	# DEFINE_boolean notag false "don't tag this release" n
+	parse_args "$@"
+	require_version_arg
+
+	# handle flags that imply other flags
+	if [ "$FLAGS_signingkey" != "" ]; then
+		FLAGS_sign=$FLAGS_TRUE
+	fi
+
+	# sanity checks
+	require_branch "$BRANCH"
+	require_clean_working_tree
+	if flag fetch; then
+		# git_do fetch -q "$ORIGIN" "$MASTER_BRANCH" || \
+		#   die "Could not fetch $MASTER_BRANCH from $ORIGIN."
+		git_do fetch -q "$ORIGIN" "lcheck" || \
+		  die "Could not fetch lcheck from $ORIGIN."
+	fi
+	# if has "$ORIGIN/$MASTER_BRANCH" $(git_remote_branches); then
+	# 	require_branches_equal "$MASTER_BRANCH" "$ORIGIN/$MASTER_BRANCH"
+	# fi
+	if has "$ORIGIN/lcheck" $(git_remote_branches); then
+		require_branches_equal "lcheck" "$ORIGIN/lcheck"
+	fi
+
+	# try to merge into develop
+	# in case a previous attempt to finish this release branch has failed,
+	# but the merge into develop was successful, we skip it now
+	if ! git_is_branch_merged_into "$BRANCH" "lcheck"; then
+		git_do checkout "lcheck" || \
+		  die "Could not check out lcheck."
+
+		# TODO: Actually, accounting for 'git describe' pays, so we should
+		# ideally git merge --no-ff $tagname here, instead!
+		git_do merge --no-ff "$BRANCH" || \
+		  die "There were merge conflicts."
+		  # TODO: What do we do now?
+	fi
+
+	if flag push; then
+		git_do push "$ORIGIN" "lcheck" || \
+			die "Could not push to lcheck from $ORIGIN."
+		# git_do push "$ORIGIN" "$MASTER_BRANCH" || \
+		# 	die "Could not push to $MASTER_BRANCH from $ORIGIN."
+		# if noflag notag; then
+		# 	git_do push --tags "$ORIGIN" || \
+		# 		die "Could not push tags to $ORIGIN."
+		# fi
+	fi
+
+	echo
+	echo "Summary of actions:"
+	echo "- Latest objects have been fetched from '$ORIGIN'"
+	# echo "- Hotfix branch has been merged into '$MASTER_BRANCH'"
+	# if noflag notag; then
+	# 	echo "- The hotfix was tagged '$VERSION_PREFIX$VERSION'"
+	# fi
+	echo "- Hotfix branch has been back-merged into 'lcheck'"
+	# if flag keep; then
+	# 	echo "- Hotfix branch '$BRANCH' is still available"
+	# else
+	# 	echo "- Hotfix branch '$BRANCH' has been deleted"
+	# fi
+	if flag push; then
+		echo "- 'lcheck' have been pushed to '$ORIGIN'"
 	fi
 	echo
 }
